name: publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: install
        run: |
          pip install poetry
          poetry install
      - name: publish
        run: |
          poetry publish -n -u __token__ -p ${{ secrets.PYPI_TOKEN }} --build
